ALTER TABLE users DROP COLUMN IF EXISTS plan;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS tier VARCHAR(50) NOT NULL DEFAULT 'freemium';
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS max_users INT NOT NULL DEFAULT 0;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS max_plans INT NOT NULL DEFAULT 0;
