package model

import (
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// SalesChannel enumeration for product sales channels
type SalesChannel string

const (
	ChannelDirect   SalesChannel = "direct"
	ChannelIndirect SalesChannel = "indirect"
)

// GeoZone enumeration for geographic zones
type GeoZone string

const (
	ZoneFrance GeoZone = "france"
	ZoneEurope GeoZone = "europe"
	ZoneExport GeoZone = "export"
)

// Product represents a product or service line
type Product struct {
	TenantScoped
	ScenarioID                uuid.UUID       `gorm:"type:uuid;not null;index" json:"scenarioId"`
	Name                      string          `gorm:"type:varchar(255);not null" json:"name"`
	SortOrder                 int             `gorm:"not null;default:0" json:"sortOrder"`
	DirectCostVariability     decimal.Decimal `gorm:"type:numeric(5,4)" json:"directCostVariability"`
	ExternalChargeVariability decimal.Decimal `gorm:"type:numeric(5,4)" json:"externalChargeVariability"`
	TaxVariability            decimal.Decimal `gorm:"type:numeric(5,4)" json:"taxVariability"`
	StaffVariability          decimal.Decimal `gorm:"type:numeric(5,4)" json:"staffVariability"`
	DepreciationVariability   decimal.Decimal `gorm:"type:numeric(5,4)" json:"depreciationVariability"`
}

// TableName specifies the table name for Product
func (Product) TableName() string {
	return "products"
}

// ProductAssumption stores cost and pricing inputs per product per year.
// Maps to P1 rows 24–35 (Key Assumptions section).
type ProductAssumption struct {
	TenantScoped
	ProductID        uuid.UUID       `gorm:"type:uuid;not null;index" json:"productId"`
	YearIndex        int             `gorm:"not null" json:"yearIndex"` // 1–5
	RawMaterialCost  decimal.Decimal `gorm:"type:numeric(15,4)" json:"rawMaterialCost"`
	RoyaltiesCost    decimal.Decimal `gorm:"type:numeric(15,4)" json:"royaltiesCost"`
	LogisticsCost    decimal.Decimal `gorm:"type:numeric(15,4)" json:"logisticsCost"`
	CostCoefficient  decimal.Decimal `gorm:"type:numeric(8,4);default:1.0" json:"costCoefficient"`
	PriceCoefficient decimal.Decimal `gorm:"type:numeric(8,4);default:1.0" json:"priceCoefficient"`
	BaseUnitPrice    decimal.Decimal `gorm:"type:numeric(15,4)" json:"baseUnitPrice"`
	IsOverridden     bool            `gorm:"not null;default:false" json:"isOverridden"`
}

// TableName specifies the table name for ProductAssumption
func (ProductAssumption) TableName() string {
	return "product_assumptions"
}

// ProductAssumptionComputed wraps ProductAssumption with computed fields.
// Not stored in DB — returned by the service.
type ProductAssumptionComputed struct {
	ProductAssumption

	// TotalUnitCost = (RawMaterialCost + RoyaltiesCost + LogisticsCost) × CostCoefficient
	TotalUnitCost decimal.Decimal `json:"totalUnitCost"`

	// FinalUnitPrice = BaseUnitPrice × PriceCoefficient
	FinalUnitPrice decimal.Decimal `json:"finalUnitPrice"`
}

// ProductSalesVolume stores sales volume input for a product × zone × channel × year combination.
// Maps to P1 rows 36–71 (Direct and Indirect Sales sections).
type ProductSalesVolume struct {
	TenantScoped
	ProductID uuid.UUID    `gorm:"type:uuid;not null;index" json:"productId"`
	YearIndex int          `gorm:"not null" json:"yearIndex"`  // 1–5
	Zone      GeoZone      `gorm:"type:varchar(20);not null" json:"zone"`
	Channel   SalesChannel `gorm:"type:varchar(20);not null" json:"channel"`
	UnitsSold int64        `gorm:"not null;default:0" json:"unitsSold"`
}

// TableName specifies the table name for ProductSalesVolume
func (ProductSalesVolume) TableName() string {
	return "product_sales_volumes"
}

// ProductDistributorMargin stores the distributor margin % per zone per year.
// Maps to P1 rows 49–71 (Indirect Sales section).
type ProductDistributorMargin struct {
	TenantScoped
	ProductID     uuid.UUID       `gorm:"type:uuid;not null;index" json:"productId"`
	YearIndex     int             `gorm:"not null" json:"yearIndex"` // 1–5
	Zone          GeoZone         `gorm:"type:varchar(20);not null" json:"zone"`
	MarginPercent decimal.Decimal `gorm:"type:numeric(8,4)" json:"marginPercent"`
	IsOverridden  bool            `gorm:"not null;default:false" json:"isOverridden"`
}

// TableName specifies the table name for ProductDistributorMargin
func (ProductDistributorMargin) TableName() string {
	return "product_distributor_margins"
}

// ProductRevenueSummary is the computed output for one product across all years.
// Matches P1 rows 5–20 (Revenue Summary section).
// Not stored in DB — generated by the compute engine.
type ProductRevenueSummary struct {
	ProductID   uuid.UUID              `json:"productId"`
	ProductName string                 `json:"productName"`
	Years       [5]ProductRevenueYear  `json:"years"`
}

// ProductRevenueYear contains annual revenue data for a product.
type ProductRevenueYear struct {
	Year      int `json:"year"`      // calendar year (e.g. 2025)
	YearIndex int `json:"yearIndex"` // 1–5

	// Row 5: Total Turnover [k]
	Turnover decimal.Decimal `json:"turnover"`

	// Row 6: Europe & Export Sales [k]
	EuropeExportSales decimal.Decimal `json:"europeExportSales"`

	// Row 7: Direct Sales [k]
	DirectSalesTotal decimal.Decimal `json:"directSalesTotal"`

	// Rows 9–15: Unit Sales breakdowns
	TotalUnitSales     int64 `json:"totalUnitSales"`     // Row 9
	FranceUnitSales    int64 `json:"franceUnitSales"`    // Row 10
	EuropeUnitSales    int64 `json:"europeUnitSales"`    // Row 11
	ExportUnitSales    int64 `json:"exportUnitSales"`    // Row 12
	CumulatedUnitSales int64 `json:"cumulatedUnitSales"` // Row 13
	DirectUnitSales    int64 `json:"directUnitSales"`    // Row 14
	IndirectUnitSales  int64 `json:"indirectUnitSales"`  // Row 15

	// Row 17: Cost of Goods Sold [k]
	COGS decimal.Decimal `json:"cogs"`

	// Rows 19–20: Gross Margin
	GrossMargin    decimal.Decimal `json:"grossMargin"`    // [k]
	GrossMarginPct decimal.Decimal `json:"grossMarginPct"` // %

	// Per-zone detail (for grid display)
	Zones [3]ProductRevenueZoneYear `json:"zones"`

	// Percentage columns (H, I in spreadsheet)
	PctOfYear1Turnover *decimal.Decimal `json:"pctOfYear1Turnover,omitempty"` // Col H
	PctOfYear3Turnover *decimal.Decimal `json:"pctOfYear3Turnover,omitempty"` // Col I
}

// ProductRevenueZoneYear contains per-zone revenue breakdown for a product in a single year.
type ProductRevenueZoneYear struct {
	Zone GeoZone `json:"zone"`

	// Direct channel
	DirectUnitsSold int64           `json:"directUnitsSold"`
	DirectUnitPrice decimal.Decimal `json:"directUnitPrice"` // final price = base × priceCoeff
	DirectRevenue   decimal.Decimal `json:"directRevenue"`   // [k]

	// Indirect channel (distributors)
	IndirectUnitsSold     int64           `json:"indirectUnitsSold"`
	EndUserPrice          decimal.Decimal `json:"endUserPrice"`          // same as direct price
	DistributorMarginPct  decimal.Decimal `json:"distributorMarginPct"`  // from ProductDistributorMargin
	CustDistributorCoeff  decimal.Decimal `json:"custDistributorCoeff"`  // 1 / (1 - margin%)
	DistributorPrice      decimal.Decimal `json:"distributorPrice"`      // end-user price × (1 - margin%)
	IndirectRevenue       decimal.Decimal `json:"indirectRevenue"`       // [k]
	CompanyGrossMarginPct decimal.Decimal `json:"companyGrossMarginPct"` // (distrib price - unit cost) / distrib price
}

// ConsolidatedRevenue aggregates all products' revenues into a company-level view.
// Matches the "Revenues" sheet in the spreadsheet.
// Not stored in DB — generated by the compute engine.
type ConsolidatedRevenue struct {
	ScenarioID uuid.UUID                  `json:"scenarioId"`
	Products   []ProductRevenueSummary    `json:"products"`
	Totals     [5]ConsolidatedRevenueYear `json:"totals"`
}

// ConsolidatedRevenueYear contains aggregated annual revenue totals across all products.
type ConsolidatedRevenueYear struct {
	Year               int             `json:"year"`
	TotalTurnover      decimal.Decimal `json:"totalTurnover"`      // sum of all products
	TotalDirectSales   decimal.Decimal `json:"totalDirectSales"`
	TotalIndirectSales decimal.Decimal `json:"totalIndirectSales"`
	EuropeExportSales  decimal.Decimal `json:"europeExportSales"`
	TotalCOGS          decimal.Decimal `json:"totalCogs"`
	TotalGrossMargin   decimal.Decimal `json:"totalGrossMargin"`
	GrossMarginPct     decimal.Decimal `json:"grossMarginPct"`
	TotalUnitSales     int64           `json:"totalUnitSales"`
}

// ProductSegmentRow represents a segment breakdown row for reporting.
type ProductSegmentRow struct {
	Label    string                `json:"label"`
	Values   [5]ProductSegmentValue `json:"values"`
}

// ProductSegmentValue holds a single segment value with unit and percent.
type ProductSegmentValue struct {
	Value   decimal.Decimal `json:"value"`
	Percent decimal.Decimal `json:"percent"`
}

// ProductUnitsRow represents a units breakdown row for reporting.
type ProductUnitsRow struct {
	Label    string              `json:"label"`
	Values   [5]ProductUnitsValue `json:"values"`
}

// ProductUnitsValue holds unit sales data with cumulative tracking.
type ProductUnitsValue struct {
	Units      int64           `json:"units"`
	Cumulative int64           `json:"cumulative"`
	Percent    decimal.Decimal `json:"percent"`
}
